### ISSUE TITLE
Compact Convolutional Neural Network Cascade

### ISSUE THREAD

**Issue by denghuiru** [Bkmz21/FD-Evaluation#1]
Hi, I have researched face detection for a period of time and feel excited that you can implement the code of this paper, however, if I want to have a quick look of the result of this code, I am not sure what to do next, your README.txt also don't give any instructions, so will you give me some instructions about how to use your code.
Best regards!

**Comment by Bkmz21** [comment]
Hi, this code used only for evaluation of face detectors on FDDB, AFW and IJB-A benchmarks or video data. It does not contain CNN detector. To view the test results it is necessary extract files from rar-archives to the root folder (Data/FDDB_TEST) and run the Matlab script.
